description: Configuration of Fall (https://github.com/lambdalisue/vim-fall)
type: object
required:
  - $schema
additionalProperties: false
properties:
  $schema:
    type: string
  input:
    $ref: "#/$defs/inputConfig"
  picker:
    $ref: "#/$defs/pickerConfig"
patternProperties:
  "^(source|transformer|projector|renderer|previewer|action)$":
    description: |
      Configuration map for the extensions of the kind.
      The key is the name and the value is the configuration.
    type: object
    additionalProperties: false
    patternProperties:
      "^[a-zA-Z0-9_\\-:]*$":
        type: object
        description: |
          An options object passed to the extension.
          See the extension's documentation for valid options.

$defs:
  inputConfig:
    description: |
      Options for the input.
    type: object
    additionalProperties: false
    properties:
      layout:
        $ref: "#/$defs/inputLayoutParams"
      redraw:
        type: object
        additionalProperties: false
        properties:
          interval:
            description: |
              The redraw interval in milliseconds.
            type: number
  pickerConfig:
    description: |
      The configuration for the picker.
    type: object
    additionalProperties: false
    properties:
      source:
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-zA-Z0-9_\\-:]*$":
            $ref: "#/$defs/sourcePickerConfig"
      action:
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-zA-Z0-9_\\-:]*$":
            $ref: "#/$defs/actionPickerConfig"
  sourcePickerConfig:
    description: |
      The configuration settings for the source picker.
    type: object
    additionalProperties: false
    properties:
      transformers:
        description: |
          The list of transformers available in the source picker.
        type: array
        items:
          type: string
      projectors:
        description: |
          The list of projectors available in the source picker.
        type: array
        items:
          type: string
      renderers:
        description: |
          The list of renderers available in the source picker.
        type: array
        items:
          type: string
      previewers:
        description: |
          The list of previewers available in the source picker.
        type: array
        items:
          type: string
      actions:
        description: |
          The list of actions available in the source picker.
        type: array
        items:
          type: string
      defaultAction:
        description: |
          The default action to perform.
        type: string
      options:
        $ref: "#/$defs/pickerOptions"
  actionPickerConfig:
    description: |
      The configuration settings for the action picker.
    type: object
    additionalProperties: false
    properties:
      transformers:
        description: |
          The list of transformers available in the action picker.
        type: array
        items:
          type: string
      projectors:
        description: |
          The list of projectors available in the action picker.
        type: array
        items:
          type: string
      renderers:
        description: |
          The list of renderers available in the action picker.
        type: array
        items:
          type: string
      previewers:
        description: |
          The list of previewers available in the action picker.
        type: array
        items:
          type: string
      options:
        $ref: "#/$defs/pickerOptions"
  pickerOptions:
    description: |
      Additional options of the picker.
    type: object
    additionalProperties: false
    properties:
      layout:
        $ref: "#/$defs/pickerLayoutParams"
      redraw:
        type: object
        additionalProperties: false
        properties:
          interval:
            description: |
              The redraw interval in milliseconds.
            type: number
      query:
        description: |
          Settings for the query.
        type: object
        additionalProperties: false
        properties:
          spinner:
            description: |
              The spinner symbols to use in the query.
            type: array
            items:
              type: string
          headSymbol:
            description: |
              The head symbol in the query.
            type: string
          failSymbol:
            description: |
              The symbol to show for failures in the query.
            type: string
      itemCollector:
        type: object
        additionalProperties: false
        properties:
          threshold:
            description: |
              The threshold of the number of items collectable.
            type: number
  inputLayoutParams:
    description: |
      The layout settings for the input window.
    type: object
    additionalProperties: false
    properties:
      width:
        description: |
          The fixed width of the input window.
          If not set, the width is calculated based on the widthRatio and the screen width.
        type: number
      widthRatio:
        description: |
          The ratio of the input window width relative to the screen width.
        type: number
      widthMin:
        description: |
          The minimum width for the input window when widthRatio is set.
        type: number
      widthMax:
        description: |
          The maximum width for the input window when widthRatio is set.
        type: number
      border:
        description: |
          The border style for the input window.
        oneOf:
          - $ref: "#/$defs/stringBorder"
          - $ref: "#/$defs/layoutBorder"
      divider:
        description: |
          The divider style for the input window.
        oneOf:
          - $ref: "#/$defs/stringDivider"
          - $ref: "#/$defs/layoutDivider"
      zindex:
        description: |
          The z-index value for the input window.
        type: number
  pickerLayoutParams:
    description: |
      The layout settings for the picker window.
    type: object
    additionalProperties: false
    properties:
      width:
        description: |
          The fixed width of the entire picker window (including preview window).
          If not set, the width is calculated based on the widthRatio and the screen width.
        type: number
      widthRatio:
        description: |
          The ratio of the entire picker window width (including preview window) relative to the screen width.
        type: number
      widthMin:
        description: |
          The minimum width for the entire picker window when widthRatio is set.
        type: number
      widthMax:
        description: |
          The maximum width for the entire picker window when widthRatio is set.
        type: number
      height:
        description: |
          The fixed height of the entire picker window. 
          If not set, the height is calculated based on the heightRatio and the screen height.
        type: number
      heightRatio:
        description: |
          The ratio of the entire picker window height relative to the screen height.
        type: number
      heightMin:
        description: |
          The minimum height for the entire picker window when heightRatio is set.
        type: number
      heightMax:
        description: |
          The maximum height for the entire picker window when heightRatio is set.
        type: number
      previewRatio:
        description: |
          The ratio of the preview window size relative to the entire picker window.
        type: number
      border:
        description: |
          The border style for the picker window.
        oneOf:
          - $ref: "#/$defs/stringBorder"
          - $ref: "#/$defs/layoutBorder"
      divider:
        description: |
          The divider style for the picker window.
        oneOf:
          - $ref: "#/$defs/stringDivider"
          - $ref: "#/$defs/layoutDivider"
      zindex:
        description: |
          The z-index value for the picker window.
        type: number
  stringBorder:
    type: string
    enum:
      - none
      - ascii
      - single
      - double
      - rounded
  stringDivider:
    type: string
    enum:
      - none
      - ascii
      - single
      - double
      - dashed
  layoutBorder:
    type: array
    items:
      - description: topleft
        type: string
      - description: top
        type: string
      - description: topright
        type: string
      - description: right
        type: string
      - description: botright
        type: string
      - description: bottom
        type: string
      - description: botleft
        type: string
      - description: left
        type: string
    minItems: 8
    maxItems: 8
  layoutDivider:
    type: array
    items:
      - description: left
        type: string
      - description: horizontal
        type: string
      - description: right
        type: string
      - description: top
        type: string
      - description: vertical
        type: string
      - description: bottom
        type: string
    minItems: 6
    maxItems: 6
$schema: "http://json-schema.org/draft-07/schema"
